package services

import (
	"backend/db"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ses"
	"github.com/aws/aws-sdk-go-v2/service/ses/types"
	"github.com/aws/aws-sdk-go-v2/service/sns"
)

// SESEmailService handles email notifications via AWS SES
type SESEmailService struct {
	client *ses.Client
	sender string
}

// SNSPushService handles push notifications via AWS SNS
type SNSPushService struct {
	client *sns.Client
}

// NotificationMetadata stores additional notification info
type NotificationMetadata struct {
	WebsiteURL   string `json:"websiteUrl,omitempty"`
	WebsiteName  string `json:"websiteName,omitempty"`
	IncidentType string `json:"incidentType,omitempty"`
	Status       string `json:"status,omitempty"`
	Latency      int    `json:"latency,omitempty"`
	Timestamp    string `json:"timestamp,omitempty"`
}

// NewSESEmailService creates a new SES email service
func NewSESEmailService() (*SESEmailService, error) {
	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		return nil, errors.New("failed to load AWS config")
	}

	client := ses.NewFromConfig(cfg)
	sender := os.Getenv("AWS_SES_SENDER_EMAIL")

	if sender == "" {
		return nil, errors.New("AWS_SES_SENDER_EMAIL environment variable not set")
	}

	return &SESEmailService{
		client: client,
		sender: sender,
	}, nil
}

// SendEmail sends an email notification
func (s *SESEmailService) SendEmail(ctx context.Context, toEmail, subject, htmlBody string) error {
	input := &ses.SendEmailInput{
		Source: aws.String(s.sender),
		Destination: &types.Destination{
			ToAddresses: []string{toEmail},
		},
		Message: &types.Message{
			Subject: &types.Content{
				Data: aws.String(subject),
			},
			Body: &types.Body{
				Html: &types.Content{
					Data: aws.String(htmlBody),
				},
			},
		},
	}

	result, err := s.client.SendEmail(ctx, input)
	if err != nil {
		return fmt.Errorf("failed to send email: %w", err)
	}

	if result == nil {
		return errors.New("send email returned nil result")
	}

	return nil
}

// SendWebsiteDownAlertEmail sends an email when a website goes down
func (s *SESEmailService) SendWebsiteDownAlertEmail(ctx context.Context, toEmail, websiteName, websiteURL string) error {
	subject := fmt.Sprintf("Alert: %s is DOWN", websiteName)
	htmlBody := fmt.Sprintf(`
		<html>
			<head></head>
			<body>
				<h2>Website Down Alert</h2>
				<p>Your website <strong>%s</strong> is currently down.</p>
				<p>URL: <a href="%s">%s</a></p>
				<p>Please check your monitoring dashboard for more details.</p>
				<p>Stay alert!</p>
			</body>
		</html>
	`, websiteName, websiteURL, websiteURL)

	return s.SendEmail(ctx, toEmail, subject, htmlBody)
}

// SendWebsiteBackUpEmail sends an email when a website comes back up
func (s *SESEmailService) SendWebsiteBackUpEmail(ctx context.Context, toEmail, websiteName, websiteURL string) error {
	subject := fmt.Sprintf("Recovery: %s is BACK UP", websiteName)
	htmlBody := fmt.Sprintf(`
		<html>
			<head></head>
			<body>
				<h2>Website Back Up</h2>
				<p>Your website <strong>%s</strong> is back online!</p>
				<p>URL: <a href="%s">%s</a></p>
				<p>Thank you for using Alive Monitoring.</p>
			</body>
		</html>
	`, websiteName, websiteURL, websiteURL)

	return s.SendEmail(ctx, toEmail, subject, htmlBody)
}

// NewSNSPushService creates a new SNS push notification service
func NewSNSPushService() (*SNSPushService, error) {
	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		return nil, errors.New("failed to load AWS config")
	}

	client := sns.NewFromConfig(cfg)

	return &SNSPushService{
		client: client,
	}, nil
}

// CreateDeviceSubscription creates a new device subscription for SNS push notifications
func (s *SNSPushService) CreateDeviceSubscription(ctx context.Context, database *db.PrismaClient, userID string, fcmToken string, deviceType string) error {
	// Save device in database
	_, err := database.Devices.CreateOne(
		db.Devices.User.Link(db.User.ID.Equals(userID)),
		db.Devices.EndpointArn.Set(""), // Will be generated by SNS
		db.Devices.FcmToken.Set(fcmToken),
		db.Devices.DeviceType.Set(deviceType),
	).Exec(ctx)

	if err != nil {
		return errors.New("failed to register device")
	}

	return nil
}

// SendPushNotification sends a push notification to a specific device
func (s *SNSPushService) SendPushNotification(ctx context.Context, endpointArn, message, title string) error {
	// This would use SNS to send to the endpoint
	// For now, return placeholder
	if endpointArn == "" {
		return errors.New("endpoint ARN is required")
	}

	return nil
}

// SendWebsiteNotificationToUser sends both email and push notification to user
func SendWebsiteNotificationToUser(ctx context.Context, database *db.PrismaClient, userID, websiteID string, notificationType string, metadata NotificationMetadata) error {
	// Get user
	user, err := GetUserByID(ctx, database, userID)
	if err != nil {
		return err
	}

	// Get website
	website, err := GetWebsiteByID(ctx, database, websiteID)
	if err != nil {
		return err
	}

	// Store notification in database
	metadataJSON, _ := json.Marshal(metadata)

	_, err = database.Notification.CreateOne(
		db.Notification.User.Link(db.User.ID.Equals(userID)),
		db.Notification.Website.Link(db.Website.ID.Equals(websiteID)),
		db.Notification.Message.Set(fmt.Sprintf("Website %s is %s", website.WebsiteName, notificationType)),
		db.Notification.Metadata.Set(metadataJSON),
		db.Notification.Status.Set(db.NotficationStatusPending),
	).Exec(ctx)

	if err != nil {
		return err
	}

	// Send email notification
	emailService, err := NewSESEmailService()
	if err == nil {
		if notificationType == "down" {
			emailService.SendWebsiteDownAlertEmail(ctx, user.Email, website.WebsiteName, website.URL)
		} else if notificationType == "up" {
			emailService.SendWebsiteBackUpEmail(ctx, user.Email, website.WebsiteName, website.URL)
		}
	}

	return nil
}

// GetWebsiteByID retrieves website by ID
func GetWebsiteByID(ctx context.Context, database *db.PrismaClient, websiteID string) (*db.WebsiteModel, error) {
	website, err := database.Website.FindUnique(db.Website.ID.Equals(websiteID)).Exec(ctx)
	if err != nil {
		return nil, errors.New("website not found")
	}

	return website, nil
}

// UpdateNotificationStatus updates notification status
func UpdateNotificationStatus(ctx context.Context, database *db.PrismaClient, notificationID, status string) error {
	statusEnum, err := parseNotificationStatus(status)
	if err != nil {
		return err
	}

	_, err = database.Notification.FindUnique(db.Notification.ID.Equals(notificationID)).Update(
		db.Notification.Status.Set(statusEnum),
	).Exec(ctx)

	return err
}

func parseNotificationStatus(status string) (db.NotficationStatus, error) {
	switch strings.ToLower(status) {
	case strings.ToLower(string(db.NotficationStatusPending)):
		return db.NotficationStatusPending, nil
	case strings.ToLower(string(db.NotficationStatusSent)):
		return db.NotficationStatusSent, nil
	case strings.ToLower(string(db.NotficationStatusFailed)):
		return db.NotficationStatusFailed, nil
	default:
		return "", fmt.Errorf("invalid notification status: %s", status)
	}
}

// GetUserNotifications retrieves all notifications for a user
func GetUserNotifications(ctx context.Context, database *db.PrismaClient, userID string, limit int) ([]db.NotificationModel, error) {
	notifications, err := database.Notification.FindMany(
		db.Notification.UserID.Equals(userID),
	).OrderBy(
		db.Notification.CreatedAt.Order("desc"),
	).Take(limit).Exec(ctx)

	if err != nil {
		return nil, err
	}

	return notifications, nil
}
