FROM node:20-alpine

WORKDIR /user/src/app

ARG BACKEND_URL
ENV NEXT_PUBLIC_API_BASE_URL=${BACKEND_URL}


COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/frontend ./

RUN npm install -g bun
RUN bun install

RUN bun run build

EXPOSE 3000
CMD ["bun", "run", "start"]